---
title: "Untitled"
author: "Jamie Ash"
date: "2022-11-04"
output: pdf_document
---

**Question 1:** For all $n \in \mathbb{N}$, show that...
$$
\frac{1}{1 \times 2} + \frac{1}{2 \times 3} + ... + \frac{1}{n(n+1)} = \frac{n}{n+1}
$$
**Question 3:** In a chess tournament of n players, each pair of players plays 
exactly one match against each other. There are no draws. Prove that the 
players can be arranged in an order $p_1, p_2...p_n$ such that $p_i$ defeats 
$p_i + 1$ for all $i = 1, 2,...n-1$

*Proof:* We proceed with strong induction. 

(Base Cases) For n total players 0 to 1 the case is null. For 2 players arrange
them as $p_1, p_2$ where $p_1$ defeated $p_2$ in a chess match.

(Inductive step) Suppose for the sake of contradiction that there is some 
smallest tournament of size $k$ where we can not arrange the players in an order 
$p_1, p_2...p_k$ such that $p_i$ defeats $p_i + 1$ for all $i = 1, 2,...k-1$

Remove one player from this player pool, while keeping all win/loss results of 
the other players the same. Let this new pool be player pool $\ell$. Pool $\ell$ 
is now $k-1$ players large, and $k-1 < k$. Since $k$ is the smallest player pool 
size that can't be arranged in such a way as described above, and $\ell$ is 
smaller than $k$, then $\ell$ can be arranged in an order $p_1, p_2...p_\ell$ 
such that $p_i$ defeats $p_i + 1$ for all $i = 1, 2,...\ell-1$. 

Arrange $\ell$ in this a way, then add a new player to the pool. Let this new 
player be player $x$. Allow player $x$ to have the same win/loss results as the 
player originaly removed from $k$. Player pool $\ell$ is now equal to player 
pool $k$. Then sequentially check if this player has defeated each player in 
$\ell$, right to left, from player $p_\ell$ to player $p_1$ in the 
$p_1, p_2...p_\ell$ standing. 

For each check of player $x$ to against player $p_i$ across players in $\ell$, 
there are two possible outcomes... 

Case 1: Player $x$ lost to a player $p_i$. Place player $x$ to the right of 
player $p_i$. The standing will maintains it's $p_i$ defeated $p_i + 1$ order. 

Case 2: Player $x$ won against player $p_i$. Now repeat this process for player 
$p_{i-1}$ ie. move to the left in the $p_1, p_2...p_\ell$. 

Now again, there are two possible outcomes to this process...

Case 1: Player $x$ lost to someone, and will be placed in the standing as 
described. The standing will maintain it's $p_i$ defeats $p_i + 1$ order.

Case 2: Player $x$ has not lost to anyone (all wins). 

If case 2 occurs, then we can place player $x$ at the front of the 
$p_1, p_2...p_\ell$ standing, so that the $p_i$ defeated $p_i + 1$ order will be 
maintained. 

Now, in all possible cases of adding the player $x$ back to pool $\ell$, so 
that $\ell = k$, we have arranged $k$ in the $p_1, p_2...p_\ell$ order in which 
player  $p_i$ has defeated player $p_i + 1$. But $k$ cannot be arranged in such
a way. This is a contradiction. Therefor there is no smallest player pool $k$
that can't be arranged in such a way. It must be that we can arrange any player 
pool of size $n \in \mathbb{N}$ in an order $p_1, p_2...p_n$ such that $p_i$ 
defeats $p_i + 1$ for all $i = 1, 2,...n-1$


**Question 4.** **Rewriting question.** 
for any $n \in \mathbb{N}$ we can write write it as $n = 2^{x_1}+2^{x_2}+...2^{x_i}$ 
where $x_0$ to $x_{i}$ are elements of the set $x \in P(\mathbb{N})$. 

(Base case) Showing 1 to 7 can be writen as $2^{x_1}+2^{x_2}+...2^{x_i}$. 
```{r, eval = FALSE}
raise = function(x){
  sum(2^x) 
}

# first few natural numbers
n = 0:2
# produce the power set of n
sets = powerSet(n, rev=TRUE)
# raise by 2 and sum each subset of n (in the powerset)
u = lapply(sets, raise)
# Just changing the data class to vector (from a list), and sriting them 
u = unlist(u)
sort(u)
```

Let $X$ be the set $\{x \in P(\mathbb{N});2^{x_1}+2^{x_2}+...2^{x_i} \}$. 
Suppose for the sake of argument that there is some $n \in \mathbb{N}$ where
$n \notin X$.  

Let $k$ be this number, and $t$ be the greatest factor of two that is less 
than $k$, and $\ell$ be the smallest factor of two greater than $k$. Such that
$t < k < \ell$ and $2t = \ell$.   

Then $k - t = m$ and $k = m + t$ where $m \in \mathbb{N}$, and $m < t < k$.  
Since $m < t < k$ and $k$ is the smallest number not in $X$, it follows that 
$t,m \in X$.  

Similarly, because $t > m$, then $t + m \in X$. 
Note, if it where the case where $m > t$ then $\ell$ would be the greatest 
factor of two that is less than $k$, not $t$.    
So $t + m = k$ and $t + m \in X$ but $k \notin X$. This is a contradiction.   
Therefore, $\forall n \in X$.   


