---
title: "Homework 8: James Ash"
output: pdf_document
---

## Part 1: Toulmin Analysis

*In your own words, what is meant in the paper by "data"? By "claim"? By "warrant"? By "backing"?*

**Data** is a accepted truths, axioms, or statements that 
have been previously proven to be true, like lemons. Similarly previews 
statemnts of a proof that have been proven true and relevant fit this bill. 

**Warrants** are miniature propositions, and are used to show
a logical step from the data to the claim. Backings are additional warrants or 
data that is provided if the a current warrant is not initially accepted as 
true by the demographic. Backings can be provided preemptively. 

A **claim** is a statement or proposition that is being presented as true. 
Claims can become data for the preseding warrant.  

*Pick two of the "Sample Proofs" on the worksheet attached, one that you think is 
good and one that is bad. Do a Toulmin analysis on these two proofs, giving the 
claim, data, and warrant for each step.*

**Proposition 2, proof 2b, good proof:**  

Step 1: 
data: "Assume $\sqrt{15} \leq \sqrt{2} + \sqrt{6}$"  
warrant: "Then... square both sides"
claim: $\sqrt{15} \leq (\sqrt{2} + \sqrt{6})^2 = 8 + 2 \sqrt{12}$

Step 2: 
data: $\sqrt{15} \leq (\sqrt{2} + \sqrt{6})^2 = 8 + 2 \sqrt{12}$  
warrant: Subtract 8 from both sides  
claim: $7 \leq 2 \sqrt{12}$  

Step 3: 
data: $7 \leq 2 \sqrt{12}$  
warrant: Square both sides
claim: $49 < 48$  

Step 3: 
data: $49 < 48$   
warrant: This is a contradiction...
claim: ...so we must have $\sqrt{2} + \sqrt{6} < \sqrt{15}$

I liked this proof because the data for each warrant was the claim from the 
previous statement, so not much digging was needed. After doing the Toulmin 
analysis I liked the proof a little less, only because the first set of data - 
warrant - claim didn't have the same structure as the preseding data - warrant - 
claim. That is, it had an equal sign in the statement rather than putting the 
result in the next line below. 

**Question 1, proof 1A, bad proof:**

Step 1:
data: no data  
warent: $n = (2k) = (2k)^2 = 4k$  
claim: so it’s divisible by 4  

The proof does not provide sufficient data for the warrant $(2k)^2 = 4k$. A 
definition of even numbers would be useful, and the assertion that $k \in Z$ is 
needed. The major gap is that $k$ is undefined. Furthermore the claim "so it's
divisible by 4" is ambiguous. It is difficult to discern what "it's" represents. 

\newpage

## Part 2: Combinatorial Proofs:

Disclaimer: I drew heavily from example 3.28 in the textbook to answer this 
question. I really like this section but also find it very difficult, and would
like to get better at doing combinatorial proofs.

Question 4: 

Show $\sum_{k=0}^{n} \binom{n}{k}^2 = \binom{2n}{n}$

$\binom{2n}{n}$ describes the number of unique permutations that can be created
by drawing n elements from a set of length $2n$. Lets call this set with length 
$2n$ set $D$.

To count the total number of unique permutations in set $D$ is we can divide $D$ 
into two equal parts $A$ and $B$, both of length $n$ so that $|A| = n$ and 
$|B| = n$. In this way $D = A \cup B$ and $A \cap B = \varnothing$. 

For any k with $0 \leq k \leq n$, because $\sum_{k=0}^{n}$, $n$ things from $D$ 
can be taken by pulling $k$ things from $A$ and $n-k$ things from $B$ for a 
total of $k+(n-k) = n$ things drawn. So that's $\binom{n}{k}$ from $A$ and 
$\binom{n}{n-k}$ things from $B$. Using the multiplication principle we find 
that's $\binom{n}{n-k}$ $\binom{n}{k}$ drawn in total from set $D$. 

$k$ can be any number from $0 to n$ so to total number of ways to select $n$ 
things from $D$ is the sum of all $k$ values as follows...


$$\binom{n}{0}\binom{n}{n-0} + \binom{n}{1}\binom{n}{n-1} + \binom{n}{2}\binom{n}{n-2}+...+\binom{n}{n}\binom{n}{0}$$
Since $\binom{n}{n-k} = \binom{n}{k}$ thgis expression becomes...

$$\binom{n}{0}\binom{n}{0} + \binom{n}{1}\binom{n}{1} + \binom{n}{2}\binom{n}{2}+...+\binom{n}{n}\binom{n}{n}$$
which can be expressed as...

$\sum_{k=0}^{n} \binom{n}{k}^2$

So I've shown two ways to count the unique permutations of set $D$ by drawing n 
elements two different ways. First as $\sum_{k=0}^{n} \binom{n}{k}^2$ and then 
as $\binom{2n}{n}$.

Therefore $\sum_{k=0}^{n} \binom{n}{k}^2 = \binom{2n}{n}$.

## Part 3: Reflection

Finally caught up with all the class work and readings after taking the trip to 
Vietnam.I find this section difficult, but would really like to improve. I like 
statistics and combinitorics seems pretty relevant to that especially with the 
binomial theorem involved. 









