---
title: "Reflection"
output: pdf_document
date: "2022-10-09"
---

Everything is good. I'm a little behind because I attended a conference in 
Vietnam for a week. I'm a little less than a week behind on the homework as of 
the writing of this reflection. I was able to keep up with the reading while I 
was away.  

The conference was called Ocean Optics XII. Most of the scientists there work 
with ocean color satellites. Ocean color satellites are a classification of 
satellites that measure the reflectance of sunlight form the ocean's surface. From
ocean reflectance, a lot of the properties of the ocean water can be inferred, most
notably the phyto-plankton* content of ocean water. I work with one of the 
satellite products, CHL, and until recently had very little knowledge of how the 
CHL satellite products is produced (I still mostly don't understand). Basically the
satellite measures the oceans reflectance with a sensor similar to a common 
camera, and from that back calculates what the light leaving the ocean would be
after accounting for atmospheric effects. There's a good bit of math and hand 
waiving involved. 

I'm mentioning all this because my master's program is coming to a close, and I'm 
thinking about pursuing a Phd. I wanted to do something more mathy, which is why
I'm taking this course, and another math class. I feel like getting into ocean 
optics could be a good path because it combines mathematics with oceanography. 
A lot of the other students at their conference were in math, physics, or 
engineering programs. 

Jamie

*phyto-plankton are plankton that photosynthesis. Plankton are any organism in
the ocean who's location/movement is subject to or dominated by the ocean 
currents. Phyto-plankton make up the base of the ocean's food web, and are 
responsible for about half the oxygen in the atmosphere. 











































